name: Feature request
description: Suggest an improvement
title: "feat: "
labels: [enhancement]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - web
        - web/cli
        - MarkdownNotes
        - documentation
        - other
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What are you trying to accomplish?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
